name: Build and Deploy
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    uses: actions/checkout@v2.3.1

    - name: Install and Build
      run: |
      pip install -r requirements.txt
      make html
 
    - name: Deploy
      uses:  JamesIves/github-pages-deply-action@4.1.4
      with:
        branch: gh-pages
        folder: build/html