name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11.2"

      - name: Install and Build
        run: |
          bash setup.sh
          python3 -m build --production
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/html # The folder the action should deploy.
